[package]
name = "lipo_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
structopt = "0.3.23"
tracing = { version = "0.1.29", features = ["max_level_trace", "release_max_level_info"] }
tracing-subscriber = "0.2.25"

lipo = { path = "../lipo" }
