[package]
name = "lipo_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dev-dependencies]
lipo = { path = "../lipo" }

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["parsing"] }
